# Generated by Django 5.2.9 on 2025-12-10 11:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_pipeline_runs',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'controls',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'frameworks',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('evidence_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('ai_classification', models.JSONField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(blank=True, db_column='control_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='audit_api.control')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='audit_api.organization')),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='ClassifierOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_controls', models.JSONField()),
                ('confidence', models.FloatField()),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(db_column='pipeline_run_id', on_delete=django.db.models.deletion.CASCADE, related_name='classifier_outputs', to='audit_api.aipipelinerun')),
                ('evidence', models.ForeignKey(db_column='evidence_id', on_delete=django.db.models.deletion.CASCADE, related_name='classifier_outputs', to='audit_api.evidence')),
            ],
            options={
                'db_table': 'classifier_outputs',
            },
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.ForeignKey(db_column='framework_id', on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='audit_api.framework'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('auth_provider', models.CharField(default='local', max_length=50)),
                ('role', models.CharField(default='user', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='audit_api.organization')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(blank=True, db_column='control_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='audit_api.control')),
                ('framework', models.ForeignKey(blank=True, db_column='framework_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='audit_api.framework')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='audit_api.organization')),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='audit_api.user')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to='audit_api.user'),
        ),
    ]
